# Generated by Django 5.1.1 on 2024-09-13 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "goal_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("calories", models.FloatField()),
                ("fat", models.FloatField()),
                ("protein", models.FloatField()),
                ("carb", models.FloatField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.users"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TodayProgress",
            fields=[
                (
                    "progress_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("date", models.DateField()),
                ("calories", models.FloatField()),
                ("fat", models.FloatField()),
                ("protein", models.FloatField()),
                ("carb", models.FloatField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="users.users",
                    ),
                ),
            ],
        ),
    ]
