# Generated by Django 5.0.6 on 2024-09-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="profile_id",
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar_link",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
