# Generated by Django 5.0.6 on 2024-08-30 23:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("meal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("image_link", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "meal_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="meal.meal"
                    ),
                ),
            ],
        ),
    ]
