# Generated by Django 5.0.6 on 2024-08-30 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("meal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("plan", models.DateTimeField()),
                ("is_done", models.BooleanField(default=False)),
                (
                    "ingredient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meal.ingredient",
                    ),
                ),
                (
                    "meal_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="meal.meal"
                    ),
                ),
            ],
        ),
    ]
