# Generated by Django 5.0.6 on 2024-08-30 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filter",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("allergy", models.CharField(max_length=255)),
                ("diet", models.CharField(max_length=255)),
                ("favorite", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("difficulty", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "ingredient_link",
                    models.CharField(
                        default="https://ppbcpbhpzrhbhikjrtbb.supabase.co/storage/v1/object/public/images/ntmcuitluhlo_1694650728.778543",
                        max_length=255,
                    ),
                ),
                ("calories", models.FloatField()),
                ("fat", models.FloatField()),
                ("protein", models.FloatField()),
                ("carb", models.FloatField()),
                ("type", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "meal_link",
                    models.CharField(
                        default="https://ppbcpbhpzrhbhikjrtbb.supabase.co/storage/v1/object/public/images/ntmcuitluhlo_1694650728.778543",
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("amount_ingredient", models.FloatField()),
                (
                    "ingredient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meal.ingredient",
                    ),
                ),
            ],
        ),
    ]
